Repository psaulnie/ft_transcendence, pull requests merged in 2023-09, with the labels that each got.

#46 change background image
  data/backend/src/entities/user.entity.ts
  data/backend/src/gateway/gateway.ts
  data/backend/src/users/users.service.ts
  data/frontend/src/components/Game/Canvas.css
  data/frontend/src/components/Game/Canvas.tsx
  data/frontend/src/components/Game/Game.tsx
  data/frontend/src/components/Game/Matchmaking.tsx
  data/frontend/src/components/Game/img/background_v1.png
  data/frontend/src/components/Game/img/brickwall.jpg
  data/frontend/src/components/Game/img/industrial.jpg
  data/frontend/src/components/Game/img/medieval.jpg
  data/frontend/src/components/Game/img/orange.jpg
  data/frontend/src/components/Game/img/scooby.jpg
  data/frontend/src/components/Global/Options.tsx
Labels: enhancement

#47 tell the user the background is changed
  data/backend/src/gateway/args.types.ts
  data/backend/src/gateway/gateway.ts
  data/frontend/src/components/Chat/ChatProcess.tsx
  data/frontend/src/components/Chat/args.types.tsx
Labels: enhancement

#62 Invite player to play pong button
  data/backend/src/gateway/args.types.ts
  data/backend/src/gateway/gateway.ts
  data/frontend/src/Base.tsx
  data/frontend/src/components/Chat/ChatProcess.tsx
  data/frontend/src/components/Chat/Message/UserOptionsMenu.tsx
  data/frontend/src/components/Chat/args.interface.tsx
  data/frontend/src/components/Chat/args.types.tsx
  data/frontend/src/components/Friendlist/Friendlist.tsx
  data/frontend/src/components/Game/Canvas.tsx
  data/frontend/src/components/Game/Game.tsx
  data/frontend/src/components/Game/Matchmaking.tsx
Labels: enhancement, invalid

#63 Matchmaking page
  data/frontend/src/components/Game/Matchmaking.tsx
Labels: enhancement

#64 Refetch stats when going to home
  data/frontend/src/components/Home/Home.tsx
Labels: enhancement

#78 Responsive game
  data/frontend/src/components/Game/Canvas.css
  data/frontend/src/components/Game/Canvas.tsx
Labels: enhancement

#109 Ban list done & functionnal
  data/backend/src/chatModule/chat.controller.ts
  data/backend/src/gateway/args.types.ts
  data/backend/src/gateway/gateway.ts
  data/backend/src/services/room.service.ts
  data/frontend/src/components/Chat/BanListDialog.tsx
  data/frontend/src/components/Chat/ChatProcess.tsx
  data/frontend/src/components/Chat/RoomOptionsMenu.tsx
  data/frontend/src/components/Chat/args.types.tsx
  data/frontend/src/store/api.tsx
Labels: enhancement

#110 Mute fixed
  data/backend/src/chatModule/chat.controller.ts
  data/frontend/src/components/Chat/Message/UserOptionsMenu.tsx
Labels: enhancement

#121 Docker fixed to run on school's mac
  data/backend/src/auth/service/auth.service.ts
  docker/backend/Dockerfile
  docker/backend/entrypoint.sh
  docker/frontend/Dockerfile
Labels: bug

#122 Blocked users fixed
  data/backend/src/chatModule/chat.controller.ts
  data/backend/src/gateway/gateway.ts
  data/backend/src/users/users.service.ts
  data/frontend/src/components/Chat/Chat.tsx
  data/frontend/src/components/Global/PrivateRoute.tsx
  package-lock.json
  package.json
Labels: bug

#126 Disable 2FA
  data/backend/src/auth/controller/twoFactorAuth.controller.ts
  data/frontend/package-lock.json
  data/frontend/package.json
  data/frontend/src/Base.tsx
  data/frontend/src/components/Global/Settings.tsx
  data/frontend/src/components/Login/TwoFactorLogin.tsx
  data/frontend/src/components/Navigation/NavDrawer.tsx
Labels: enhancement

#152 Remove user test
  data/backend/src/app.module.ts
  data/backend/src/gateway/gateway.ts
  data/backend/src/services/room.service.ts
  data/frontend/src/components/Chat/Chat.tsx
  data/frontend/src/components/Global/Settings.tsx
  data/frontend/src/components/Login/Login.tsx
  data/frontend/src/components/Login/TwoFactorLogin.tsx
Labels: bug, enhancement
